import type { ClassroomResource } from "@/lib/types";

export const classroomResources: ClassroomResource[] = [
  {
    slug: "ip-foundations",
    title: "一小时读懂乡村经营中的知识产权",
    kind: "课程",
    format: "文章",
    level: "入门",
    summary: "从一枚商标、一张照片和一次联名出发，建立知识产权基础框架。",
    duration: "12 分钟",
    articleSlug: "trademark-registration-basics",
  },
  {
    slug: "gi-protection-practice",
    title: "地理标志保护与规范用标实务",
    kind: "课程",
    format: "文章",
    level: "实务",
    summary: "讲清不同保护路径、申请准备和授权后的质量治理。",
    duration: "18 分钟",
    articleSlug: "geographical-indication-roadmap",
  },
  {
    slug: "intangible-heritage-toolkit",
    title: "非遗知识产权保护工具箱",
    kind: "手册",
    format: "文章",
    level: "进阶",
    summary: "用保护矩阵识别创作、标识、工艺与经营信息的不同策略。",
    duration: "15 分钟",
    articleSlug: "intangible-heritage-rights-matrix",
  },
  {
    slug: "ai-creation-guide",
    title: "AI 辅助创作合规使用指南",
    kind: "手册",
    format: "文章",
    level: "实务",
    summary: "从输入到发布的过程记录、来源核验和风险审查。",
    duration: "14 分钟",
    articleSlug: "ai-content-evidence-card",
  },
  {
    slug: "aigc-yixiu-wang-hui",
    title: "AIGC技术赋能呷古彝绣产业化转型发展",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "从民族文化产业转型视角观察 AIGC 对非遗生产、传播与品牌塑造的影响。",
    duration: "PDF 原文",
    author: "王慧",
    theme: "AIGC 与非遗产业化",
    resourceUrl: "/resources/aigc-yixiu-wang-hui.pdf",
  },
  {
    slug: "aigc-chengdu-rural-revitalization-wang-tao",
    title: "AIGC技术助力成都乡村振兴发展策略研究",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "聚焦 AIGC 在乡村产业、治理与文旅融合中的落地路径和现实约束。",
    duration: "PDF 原文",
    author: "汪涛",
    theme: "AIGC 与乡村振兴",
    resourceUrl: "/resources/aigc-chengdu-rural-revitalization-wang-tao.pdf",
  },
  {
    slug: "attraction-asset-rights-digital-era-zuo-bing",
    title: "从景观到景像：数字时代吸引资产权再探讨",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "讨论数字化文旅吸引物、景观资源与吸引资产权在数字时代的权属问题。",
    duration: "PDF 原文",
    author: "左冰",
    theme: "数字文旅与资产权",
    resourceUrl: "/resources/attraction-asset-rights-digital-era-zuo-bing.pdf",
  },
  {
    slug: "leisure-agriculture-ip-protection-guan-sijia",
    title: "高质量发展下我国休闲农业知识产权保护研究",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "围绕休闲农业知识产权保护的现实困境、制度供给与治理路径展开分析。",
    duration: "PDF 原文",
    author: "管思佳",
    theme: "休闲农业知识产权",
    resourceUrl: "/resources/leisure-agriculture-ip-protection-guan-sijia.pdf",
  },
  {
    slug: "ai-innovation-value-chain-wang-jingjing",
    title: "人工智能发展赋能创新价值链升级——基于新质生产力与知识产权保护的视角",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "从新质生产力与知识产权保护角度解释人工智能对创新价值链升级的作用机制。",
    duration: "PDF 原文",
    author: "王菁菁",
    theme: "人工智能与创新价值链",
    resourceUrl: "/resources/ai-innovation-value-chain-wang-jingjing.pdf",
  },
  {
    slug: "ai-ip-information-service-ji-kaiyi",
    title: "人工智能技术赋能知识产权信息服务的理论研究现状和实践应用策略",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "梳理 AI 技术进入知识产权信息服务的理论基础、应用场景与实践策略。",
    duration: "PDF 原文",
    author: "纪恺祎",
    theme: "知识产权信息服务",
    resourceUrl: "/resources/ai-ip-information-service-ji-kaiyi.pdf",
  },
  {
    slug: "ai-driven-ip-protection-han-shuo",
    title: "人工智能驱动下的知识产权保护机制建设研究",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "关注人工智能背景下知识产权创造、管理、服务与保护机制的系统建设。",
    duration: "PDF 原文",
    author: "韩硕",
    theme: "AI 驱动保护机制",
    resourceUrl: "/resources/ai-driven-ip-protection-han-shuo.pdf",
  },
  {
    slug: "aigc-guizhou-ethnic-brand-gan-rui",
    title: "生成式人工智能技术赋能贵州民族文化产业品牌发展研究",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "以贵州民族文化产业品牌为对象，分析生成式 AI 带来的品牌传播与治理议题。",
    duration: "PDF 原文",
    author: "甘蕊",
    theme: "生成式 AI 与民族文化品牌",
    resourceUrl: "/resources/aigc-guizhou-ethnic-brand-gan-rui.pdf",
  },
  {
    slug: "digital-cultural-tourism-resource-protection-li-min",
    title: "数字赋能文旅资源动态保护与活态利用研究",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "从动态保护与活态利用角度讨论文旅资源数字化转化的治理路径。",
    duration: "PDF 原文",
    author: "李敏",
    theme: "数字文旅资源保护",
    resourceUrl: "/resources/digital-cultural-tourism-resource-protection-li-min.pdf",
  },
  {
    slug: "ai-era-ip-protection-li-yanlin",
    title: "探索人工智能时代下的知识产权保护机制建设",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "讨论人工智能时代知识产权客体、权属与保护机制更新的制度议题。",
    duration: "PDF 原文",
    author: "李彦林",
    theme: "人工智能时代知识产权",
    resourceUrl: "/resources/ai-era-ip-protection-li-yanlin.pdf",
  },
  {
    slug: "agricultural-data-rights-sun-shan",
    title: "我国农业数据发展现状及确权必要性",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "聚焦农业数据资源发展现状、确权必要性与数据要素价值释放。",
    duration: "PDF 原文",
    author: "孙姗",
    theme: "农业数据确权",
    resourceUrl: "/resources/agricultural-data-rights-sun-shan.pdf",
  },
  {
    slug: "new-quality-productivity-agri-ip-li-erhong",
    title: "新质生产力视阙下河南省农业知识产权赋能乡村振兴的路径研究",
    kind: "论文",
    format: "PDF",
    level: "研究",
    summary: "从新质生产力视角分析农业知识产权赋能乡村振兴的地方实践路径。",
    duration: "PDF 原文",
    author: "李二红",
    theme: "新质生产力与农业知识产权",
    resourceUrl: "/resources/new-quality-productivity-agri-ip-li-erhong.pdf",
  },
];
