import type { ClassroomResource } from "@/lib/types";

export const classroomResources: ClassroomResource[] = [
  {
    slug: "ip-foundations",
    title: "一小时读懂乡村经营中的知识产权",
    kind: "课程",
    format: "文章",
    level: "入门",
    summary: "从一枚商标、一张照片和一次联名出发，建立知识产权基础框架。",
    duration: "12 分钟",
    articleSlug: "trademark-registration-basics",
  },
  {
    slug: "gi-protection-practice",
    title: "地理标志保护与规范用标实务",
    kind: "课程",
    format: "文章",
    level: "实务",
    summary: "讲清不同保护路径、申请准备和授权后的质量治理。",
    duration: "18 分钟",
    articleSlug: "geographical-indication-roadmap",
  },
  {
    slug: "intangible-heritage-toolkit",
    title: "非遗知识产权保护工具箱",
    kind: "手册",
    format: "文章",
    level: "进阶",
    summary: "用保护矩阵识别创作、标识、工艺与经营信息的不同策略。",
    duration: "15 分钟",
    articleSlug: "intangible-heritage-rights-matrix",
  },
  {
    slug: "ai-creation-guide",
    title: "AI 辅助创作合规使用指南",
    kind: "手册",
    format: "文章",
    level: "实务",
    summary: "从输入到发布的过程记录、来源核验和风险审查。",
    duration: "14 分钟",
    articleSlug: "ai-content-evidence-card",
  },
  {
    slug: "fieldwork-report-2026",
    title: "2026 五省区调研综合报告",
    kind: "报告",
    format: "PDF",
    level: "进阶",
    summary: "汇总调研方法、主要发现、典型场景与政策建议。原始报告接入后开放预览与下载。",
    duration: "待发布",
  },
  {
    slug: "policy-materials",
    title: "农文旅融合政策资料汇编",
    kind: "政策文件",
    format: "PDF",
    level: "实务",
    summary: "按主题整理政策原文与检索信息。原始文件接入后开放预览与下载。",
    duration: "待发布",
  },
];
